### ISSUE TITLE
Discussion: login

### ISSUE THREAD

**Issue by Redcxx** [dazuling/pixiv-api#1]
Hey there, I am working on a similar project on Pixiv called [Pikax](https://github.com/Redcxx/Pikax). my api could not login into Pixiv from about 1 weeks ago. I see alot of people are using `https://oauth.secure.pixiv.net/auth/token`, however, I do not quiet understand how it works, do you mind make a little explaination to me? Thanks

**Comment by dazuling** [comment]
It is an OAuth endpoint to authenticate with the Pixiv API used by their mobile applications. Thus, it returns an access token and refresh token, the latter of which can be used to generate new access tokens. These access tokens can be used to make requests to other endpoints in the API. If you are making requests to the browseable website, afaik the access tokens won't work. I believe my code is fairly clear in showing the exact request it makes.

**Comment by Redcxx** [comment]
Thanks! I will have a closer look at your code and try to understand it more!
